[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "redcheck"
version = "0.2.0"
authors = [
  { name="Nikki", email="nikki@example.com" },
]
description = "AI Guardrail engine for LLM output evaluation and hallucination detection"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openai>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/IzzyFrameworks/RedCheck"
"Bug Tracker" = "https://github.com/IzzyFrameworks/RedCheck/issues"
